upload deps to Release

diff --git a/.github/workflows/build-deps-ubuntu.yml b/.github/workflows/build-deps-ubuntu.yml
--- a/.github/workflows/build-deps-ubuntu.yml
+++ b/.github/workflows/build-deps-ubuntu.yml
@@ -7,12 +7,31 @@ on:
         description: 'Branch to build'
         required: true
         default: 'master'
+      release_tag:
+        description: 'Existing Release tag to upload to'
+        required: true
 
 jobs:
   build:
     runs-on: ubuntu-latest
+    permissions:
+      contents: write
 
     steps:
+    - name: Check if Release tag exists
+      id: check_release
+      run: |
+        RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" \
+          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+          -H "Accept: application/vnd.github.v3+json" \
+          "https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ github.event.inputs.release_tag }}")
+        if [ "$RESPONSE" -ne 200 ]; then
+          echo "Release tag not found: ${{ github.event.inputs.release_tag }}"
+          exit 1
+        else
+          echo "Release tag exists: ${{ github.event.inputs.release_tag }}"
+        fi
+
     - name: Check out code
       uses: actions/checkout@v4
 
@@ -45,11 +64,15 @@ jobs:
           ghcr.io/zerolover/github-action/lo:v0.1 \
           /bin/bash /workspace/script/build-deps-ubuntu.sh
 
-    - name: List dolphin directory contents
-      run: ls -la dolphin
+    - name: Compress the output
+      run: |
+        tar -cJf deps_ubuntu_${{ github.event.inputs.branch }}_${{ env.commit_id }}.tar.xz deps/
 
-    - name: Upload build artifacts
-      uses: actions/upload-artifact@v4
+    - name: Upload build artifacts to Existing Release
+      uses: softprops/action-gh-release@v2
       with:
-        name: dolphin-${{ github.event.inputs.branch }}-${{ env.commit_id }}
-        path: dolphin
+        tag_name: ${{ github.event.inputs.release_tag }}
+        files: deps_ubuntu_${{ github.event.inputs.branch }}_${{ env.commit_id }}.tar.xz
+        overwrite: true
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
